name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      - prod
      - change_deploy_flows
    paths:
      - 'infra/**'

jobs:
  test-lint:
    uses: ./.github/workflows/test-and-lint.yml
    name: Test and Lint
    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  terraform:
    name: Deploy
    runs-on: ubuntu-22.04
    needs: [test-lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set vars
        run: |
          if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
            echo "prod" > .workspace
          else
            echo "staging" > .workspace
          fi

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
          TF_VAR_django_secret_key: ${{ secrets.TF_VAR_DJANGO_SECRET_KEY }}
        run: |
          export TF_VAR_ecr_app_image="nginx:latest"
          export TF_VAR_ecr_proxy_image="nginx:latest"
          workspace=$(cat .workspace)
          cd infra/infra
          docker compose run --rm terraform -chdir=deploy init -reconfigure
          docker compose run --rm terraform -chdir=deploy workspace select -or-create $workspace

      - name: Terraform Plan
        run: |
          cd infra/infra
          docker compose run --rm terraform -chdir=deploy plan

      - name: Terraform Apply
        run: |
          cd infra/infra
          docker compose run --rm terraform -chdir=deploy apply -auto-approve

      - name: Get ECS names
        run: |
          cd infra/infra
          CLUSTER=$(docker compose run --rm terraform -chdir=deploy output -raw ecs_cluster_name)
          SERVICE=$(docker compose run --rm terraform -chdir=deploy output -raw ecs_service_name)
          echo "CLUSTER=$CLUSTER" >> $GITHUB_ENV
          echo "SERVICE=$SERVICE" >> $GITHUB_ENV
